Fix: Include the necessary header for assert macro definition
Otherwise compiling with aggressive optimization flag -DNDEBUG the
compilation with GCC produces the following diagnostics warning:

    > warning: implicit declaration of function ‘assert’
    > [-Wimplicit-function-declaration]

and later linking fails with error:

    > undefined reference to `assert'

In case of Clang 20 and -Werror, the compilation simply fails with:

    > error: call to undeclared function 'assert'; ISO C99 and later do
    > not support implicit function declarations
    > [-Wimplicit-function-declaration]

This problem probably went unnoticed because Red Hat doesn't force
NDEBUG in their RPM builds. For example, on CentOS Stream 9:

    $ rpm --showrc | grep NDEBUG
    $

The Fedora and EPEL RPM specs for lttng-tools package don't do anything
special regarding NDEBUG:
* https://src.fedoraproject.org/rpms/lttng-tools/blob/f42/f/lttng-tools.spec
* https://src.fedoraproject.org/rpms/lttng-tools/blob/epel9/f/lttng-tools.spec

Despite not including <assert.h> in the files affected by this commit,
the default (no -DNDEBUG) build succeeds because of including urcu.h
which transitively includes assert.h. However, when NDEBUG is defined,
the urcu.h won't include assert.h anymore.

Here is how the affected files were selected for this change:

    git grep -l 'include.*assert' | sort > includes.txt
    git grep -l '\<assert\s*(' | sort > uses.txt
    grep -F -v -f includes.txt uses.txt

Some files from the collected list were skipped, as they don't need the
include fix.